### ISSUE TITLE
5.0b1 Layout Options  Preview and Save dont Work (scss)

### ISSUE THREAD

**Issue by thomaskieslich** [Typesetter/Typesetter#107]
Change a Variable in Layout Options (Bootswatch_scss) $body-bg: #00f !default; 
Preview and Save has no Effect.

btw. I love Version 5

**Comment by oyejorge** [comment]
Try ```$body-bg: #00f;```

I think it makes sense to remove all of the ```!default``` flags that show up in the layout editor

**Comment by thomaskieslich** [comment]
It don't help, my first test was with the foundation settings.scss without the !default Flags. It should work with and without !default.

**Comment by juek** [comment]
Er... a stupid question: Do we now also have SASS processor aboard?

**Comment by thomaskieslich** [comment]
YES

**Comment by juek** [comment]
OMG ;o)

**Comment by oyejorge** [comment]
> It should work with and without !default.

That would be nice, but it depends on the order the scss is defined as well (ie, the order the scss files are included). The following has two different results when compiling the scss:

```scss
$body-bg: #fff;
$body-bg: #000 !default;
```

```scss
$body-bg: #fff;
$body-bg: #000;
```
So we can order the scss one of two ways:

1. Variables.scss
2. custom scss from layout editor (without using !default)
3. Bootstrap.scss

or

1. custom scss from layout editor
2. Variables.scss (using !default)
3. Bootstrap.scss

I'm leaning towards using the first option since it doesn't require users to remember to use !default everywhere they want to set a variable value.

> Josh, you tell us when we need a dedicated server for TS, don't you?

For TS installations? Never. I've been able to improve the performance of the Scss compiler well beyond what I was able to do with the Less compiler so it should even work on servers with restricted memory limits.

**Comment by thomaskieslich** [comment]
I think the variables.scss should only used in the "Edit Layout" Area and can contains bootstrap/foundation settings or custom variables. The ordering should be done with imports in the styles.scss.
The main problem is if i change the variables.scss in  "Edit Layout" the changes are not saved.

**Comment by oyejorge** [comment]
> I think the variables.scss should only used in the "Edit Layout" Area

That won't work. The variables.scss files define a lot of default colors and dimensions for themes. [Take one of the bootswatch themes](https://github.com/Typesetter/Typesetter/tree/dev/themes/Bootswatch_Scss/Cerulian). Without the variables.scss file, the theme would just have a generic bootsrap look.

> The main problem is if I change the variables.scss in "Edit Layout" the changes are not saved.

Ah, I see it. After reloading the layout editor, the edited values are no longer there.
