### ISSUE TITLE
Add HTMLPurifier as library for XSS prevention

### ISSUE THREAD

**Issue by JPustkuchen** [Typesetter/Typesetter#153]
Hi all,

I'd like to suggest to add HTMLPurifier (http://htmlpurifier.org standalone or lite ) as standard library for XSS prevention in typesetter output.
On this page http://htmlpurifier.org/comparison you can see why I think it would be very useful for all plugins and the Typesetter core.
strip_tags and htmlspecialchars don't cove all situations. For example if you'd like to output allowed tags for administrators. strip_tags would always also allow javascript attributes even when blocking <javascript> elements.

We should not re-invent the wheel but use a proper standard and make it available to all Typesetter developers by default. What do you think?

**Comment by juek** [comment]
Hi Julian, 

as you might have seen, Josh added (a now quite old version of) [kses](https://github.com/Typesetter/Typesetter/blob/master/include/thirdparty/wp/kses.php) some 6 years ago, but as far as I can see, it was never used. HTMLPurifier is clearly a mighty library, but it is also very large and probably rather resource hungry. 

Since we only had a few XSS vulns over the years and I cannot recall anything really critical, I'm currently not willing to add, test and maintain a HTMLPurifier implementation. 

In case you already made a working implementation yourself and there are benchmarks, especially in terms of memory usage, I'd be interested in a pull request.

I'll close this issue for now.
