### ISSUE TITLE
A proposal

### ISSUE THREAD

**Issue by ghost** [Typesetter/Typesetter#168]
For people who want to develop or change templates it would be easier to have a point 'styleclass' in the submenu of 'deatails - More Options' for each link . Of course it must be seperat saved for each template - as a file in the specific template directory like style.cfg

**Comment by juek** [comment]
If I understand it correctly, this is what we have Layouts for. You can add custom styles in Layout Editor, create copies of Layouts with different styles and apply them to the pages you want. 

Layout css (scss/less) will be saved in /data/_layouts/[123abc] 
Typesetter does not save anything outside the /data directory and it normally doesn't have write access to - let's say - /themes/Bootswatch_Scss 

 'Details -> More Options' contains page specific data. What kind of information would you like to input here? Page-specific css?

**Comment by gvoxcms** [comment]
Its just for  styling specific links with a class

**Comment by gvoxcms** [comment]
I have a problem(..) with import of backups. If i have an installation into a directory /sub1
and the new installation is in /sub2 then the path /sub1/_uplads/.. is still in the backup and must be corrected manually(especially with images).
On can create a variable $up with /sub1/_uploads/ an use the $up/images/..jpg
This can make typesetter more **portable** - the same ist with the long directory path htdocs/sub1 or similar(var/www....). This path could be saved in a variable and automatically updated by the system after restore in a new directory. - for Typesetter 5.1

**Comment by juek** [comment]
> If i can add a class like cls1 then i can add 'cls1 id=id1 attr=at1 data-type=..' If the editor does accept this
> it gives me a lot of possibilities - and li with class cl1 > a ... So i can format anchors

You can do that in Layout Editor:
Ii the CSS(/SCSS/LESS) area on the right you can add arbitrary class and id declarations such as …

```
li.cls1 { display:inline-block; margin: 4px;  }
li.cls1 > a { display:block; background:#333; color:#ccc; padding:1em 2em; }

```
Then add your class to the li element like 
<ul><li **class="cls1"**><a href="#">Anchor</a></li><li>[...]</li></ul> 
via CK Editor's HTML Source.

The "cls1" class will apply on all pages using the layout you added the rule (via Layout Editor).

**Comment by juek** [comment]
> I have a problem(..) with import of backups. If i have an installation into a directory /sub1 and the new installation is in /sub2 then the path /sub1/_uplads/.. is still in the backup and must be corrected manually(especially with images). [...] This path could be saved in a variable and automatically updated by the system after restore in a new directory. - for Typesetter 5.1(portable)

I totally agree. This is a well known issue and bothers me as well. Unfortunately it is not trivial to solve.
We actually have this variable, it's $dirPrefix. The problem is that CK Editor is not aware of it so we would have to parse and filter all generated content upon saving and detect the subdirectory part in posted content URLs (relative and absolute ones). But I will keep it in mind and maybe find a way to implement it.

Currently the best solution to prevent this issue is to avoid subdirectory installations but use virtual hosts and subdomains like http://dev1.myTypesetterWebsite.com in the development process instead.

**Comment by gvoxcms** [comment]
A possibility is to add a funtions.php in the index.php  with an entry str_replace( oldsub, newsub, text) or similar. 
Another posssibilty is to store the /sub1 in the database  so that it is contained in the backup and create a variable with the momentary /sub (which is the present in the new installation) After automatic comparing both a strings the system can replace it automatic in some php-file with str_replace() and  compensate this so.

**Comment by juek** [comment]
> str_replace( oldsub, newsub, text)

This would replace any occurence of - let's say - '/sub1' anywhere, also e.g. in '.../images/sub1.jpg', and it would slow the whole CMS down. Typesetter doesn't parse/filter all the content when serving pages, which is one of the key factors why it is so fast and consumes very low ressources. 
Replacement would have to be done when saving content, not when serving it. Replacing subdirecory occurences when creating or restoring exports would not solve the issue when whole site is simply copied from a subdir to another or to the server root. In the latter case url-rewriting rules in .htaccess must also be changed.

**Comment by juek** [comment]
FYI: I myself made exactly the same proposal [in the Typesetter Feedback area](https://www.typesettercms.com/Feedback?id=121) some 2 years ago. Unfortunately Josh (the maker of Typesetter) didn't pick it up since. 
In the menatime I made some headway with Typesetter's code and maybe I can manage to implement it myself. I will have to try it and test it extensively - trouble-free functioning is crucial and any errors at this level of the CMS might break a whole website.
