### ISSUE TITLE
Feature request: section wrapper links

### ISSUE THREAD

**Issue by freedomlives** [Typesetter/Typesetter#183]
This could perhaps be done with a plugin as well, but while I can figure out right now just enough javascript and PHP to be dangerous, and modify existing plugins to create new sections, I don't see how to make a "section wrapper" type section through a plugin.
Basically, what I'd want to do is something like this:
http://test.freedomlives.net/rectangles.html
Codewise, each square looks like this:
```html
<a href="/1.html">	
    	<div class="col-xs-4">
    	<div class="caption">	
    		<h3 >Some text</h3>
    		<p class="hidden-sm hidden-xs">A longer description, which shouldn't show up on small viewports.</p>
    	</div>
    	<img src="/img/square/1.jpg" >
    	</div>
    </a>
```
And its done, simple, just wrap each column in an <a> and everything works.
Extended to Typesetter, it would mean text would just be a normal text section, image could be a normal image, could be e.g. the parallax plugin, potentially even a video background.  Then just put on each element the right CSS classes, and set as an option on section wrapper a link URL.

**Comment by freedomlives** [comment]
One of the reasons for wanting to do it this way (vs just making images with text in them) is precisely the hiding options bootstrap gives based on screen size.

**Comment by thomasfrobieter** [comment]
So if i understand you correctly, you would like to choose the HTML Element of a section wrapper? That would imply to have the ability to set up the (allowed) attributes of the element also. I'm not sure if it's a really good idea as section wrappers should be just simple wrappers in my opinion. 

I would recommend using Custom Sections (https://github.com/juek/CustomSections) or especially for the example above: http://typesetter-addons.grafikrausz.at/Responsive_Image

**OT Hint:** As of my knowledge, <a> is still an inline element, as of the HTML5 specification it's not allowed to use it as block element. In a early draft of the specification it was allowed, but they changed it.

**Comment by thomasfrobieter** [comment]
BUT choosing simply the element itself would be great to have more semantic markup (https://www.w3schools.com/html/html5_semantic_elements.asp).

**Comment by freedomlives** [comment]
@thomasfrobieter I guess that would be the other way.  I had read the other day though that the <a> can wrap entire sections: https://www.w3.org/TR/html5/text-level-semantics.html#the-a-element

**Comment by freedomlives** [comment]
Oh, wait, what I mean, is that the section wrapper would still create a <div>, but outside that <div> would go an <a>

**Comment by juek** [comment]
Unfortunately we don't have a way to define custom, functional wrapper sections. I totally agree that they would come in handy from time to time, e.g. in your case, but on the other hand I can see how our plain wrapper sections frequently cause confusion. So I fear that additional wrapper types might cause even more.

For wrapping several sections with an anchor: Yes, HTML5 allows that but it will make editing them difficult because it will catch every click inside it. 

A JavaScript workaround could be sth. like …

Add a css class to the clickable wrapper, e.g. 'link-wrapper'

Add an attribute 'data-link' with the href as value 
OR
Add a generic <a href="/your/link">…</a> to your caption text

Add this line somewhere to your template.php:

$page->jQueryCode .= '
$("body:not(.gpAdmin) .link-wrapper").each( function(){
  var link = $(this).attr("data-link") || $(this).find("a").first().attr("src");
  if ( link ){
    $(this)
      .css("cursor","pointer")
      .on("click", function(){ window.location.href = link; }
  }
}
';

This will only catch the click if you're not logged in.

**Comment by freedomlives** [comment]
Wow.  This is good.  I really need to get proficient in javascript and then jquery.  It looks like magic. :-)

**Comment by juek** [comment]
Hope it works. Didn't test the code (but already used similar several times).
Adding an anchor to the caption variant is the way to go for the noscript folks out there.

**Comment by freedomlives** [comment]
Missing a couple of parenthesis.  Once those got in, it works great!
```javascript
$page->jQueryCode .= '
$("body:not(.gpAdmin) .link-wrapper").each( function(){
var link = $(this).attr("data-link") || $(this).find("a").first().attr("src");
if ( link ){
$(this)
.css("cursor","pointer")
.on("click", function(){ window.location.href = link; })
}
})
';
```
