### ISSUE TITLE
Editing error

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#205]
I have some rare problem with page editing. Also I have some very specific conditions to reproduce this error: slow wi-fi connection + slow Atom netbook + such "rich" page content :)

I have page with structure "Text + Slider Factory + Text + Slider Factory + Text + Slider Factory".

After editing of  Slider Factory (deleted inner text wrappers and changed images in backgrounds) one slide become to be grey sometimes . In editor I can choose image for this responsive background but it don't changing.
I have deleted _ill_ slide and copied _healthy_ one. But then some another slide becomes to be grey.

P.S.
With previous TS beta I had another problem.
After editing of second and following Text, sections sometimes changed to Section Wrapper.
With last Master release Text section **became to be stable in editing**!
So I think the source of problem is not in Slider Factory

**Comment by juek** [comment]
> So I think the source of problem is not in Slider Factory

No, its rather the Responsive Image backgrounds which may fail to trigger the needed events in time when images are fully loaded. This tends to happen especially when lots of them are uses and the connection is slow. Quite hard to bebug because quite some events fire asyncronously and may interfere with other operations that cause DOM re-evaluation which I suspect to interfere with load events. 

But, from my experience, manual changing the window size (e.g. hitting F11 two times) which triggers a window.resize event, forces all RI sections to update and mostly fixes the display issues. 

> After editing of second and following Text, sections sometimes changed to Section Wrapper.

Also a known issue which I currently have no clue how to get completely rid of. With many sections Typesetter sometimes messes them up when saving. The more sections the more frequently it occurs. Must also be some kind of timing issue and DOM parsing. It messes up the posted section_order array. It's also quite hard to reproduce and debug and very annoying. Normally rquires to to roll back to a former page revision to fix the page.

> With last Master release Text section became to be stable in editing!

I do not believe that recent changes actually improved it.

**Comment by mahotilo** [comment]
> But, from my experience, manual changing the window size (e.g. hitting F11 two times) which triggers a window.resize event, forces all RI sections to update and mostly fixes the display issues.

Thx, I'll try it

> Normally rquires to to roll back to a former page revision to fix the page.

Yes, it'is the only salvation

> I do not believe that recent changes actually improved it.

I can't say exactly but previous beta version was about 1 month old.
Error with Text -->Wrapper was stable. I did 3 tries to edit page and all of them ended with error and restoration from backup. After update to last Master error disappears.

My workaround for now is "patience". If I do all editing with time-outs for autosaving, errors does't appear.

**Comment by juek** [comment]
Yes, patience it (unfortunately) the gold standard for now.
