### ISSUE TITLE
Proposal for Gallery Editing

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#207]
In TS < 5 it was possible to delete/edit caption gallery images directly in page. 
In true WYSIWYG style. 
Now we can do it only in sidebar, unfortunately. It is too hard to find needed image if your gallery have more then 10 and similar images.
Can the old way of editing the gallery be returned someday?
Or there is serious barriers for this?

**Comment by juek** [comment]
> ... In true WYSIWYG style ... Now we can do it only in sidebar, unfortunately. 

I agree. It was very intuitive.

> Can the old way of editing the gallery be returned someday? Or there is serious barriers for this?

Since TS 5 we have 'page level' editing of several sections in a single 'editing session' (unless the editor is closed).  This works quite different than before because the now multiple, simultaneous active editor comonents are not only loaded dynamically but also cached, 'set asleep' and 're-awakened' when switching between sections. Pretty awesome programming I couldn't have done myself! 

Galleries are the most complex section types we have aboard. Unbinding/rebinding lots of JavaScript events, object states and -data can become complex. I believe this is the reason why Josh sacrificed some direct interaction with edited section content, which had to have several JS events attached to it earlier.

With large amounts of content and section types used in parallel, IMO we already reached a certain critical point where in-page, live editing becomes hard to handle in terms of ressources, timing and code complexity - in order to to remain fluid and reliable. 

So, I fear the old behavior won't come back.

**Comment by mahotilo** [comment]
Ok. I understood. But may we have some workaround? We can open Source in big modal window. Is it possible to have such possibility for gallery editor?

**Comment by juek** [comment]
It would be possible basically but quite hazardous if not doen properly. Gallery source code is very specific and must remain intact ant consistent in order not to confuse or even break the editor. A single markup error could potentially break everything here. 

CKEditor's Source dialog takes care of HTML consitency and 'wellformedness' of the edited HTML but not much more. For a safe gallery source code editor, we would have to make it check for, report or auto-fix any invalid gallery markup structure errors. That's nothing to be coded just like that. 

For larger bulk changes, I sometimes need to edit the respective page.php via FTP/SCP/...
Of course it needs to be done with caution and preferably keeping a backup.

**Comment by mahotilo** [comment]
Probably, I did not speak clearly. 
I mean not source editor for gallery. I want to talk about possibility to "open" field with images thumbs. I mean a Bigger (pop-up) window to edit images order and captions in modal mode? Maybe in Iframe?
Something like on my awkward mockup:)
![1](https://user-images.githubusercontent.com/14929385/29190405-b433bd1c-7e22-11e7-97b1-c9cb0c7ece18.png)

**Comment by juek** [comment]
Ok, i see. Yes, that's the problem with arbitrary aspect ratio thumbs, especially wen they are quite wide or tall. What if you simply add this to your layout css:

#gp_current_images div, #gp_gallery_avail_imgs div {
    width: 48%!important;
}

Makes the editor thumbnails 2-column instead of 3.

**Comment by mahotilo** [comment]
Oh, thanks. It looks nicer.
I do not want to be intrusive, but what do You think about to open `ckeditor_wrap` in wide Iframe and showing only `gp_current_images`? Maybe it bring us to JS events mess? Or vice versa?
Or can we allow to user maximize `ckeditor_wrap`?

**Comment by juek** [comment]
An iframe is not an option. But it should be relatively easy to 'outsource' #gp_current_images to a gpAdminBox. Gimme a few minutes... ;-)

**Comment by juek** [comment]
Funky - seems to work:

[GalleryEditorTweaks_1_0.zip](http://typesetter-addons.grafikrausz.at/data/_uploaded/file/GalleryEditorTweaks_1_0.zip)

**Comment by juek** [comment]
... see also the [GitHub Repo](https://github.com/juek/GalleryEditorTweaks/)

**Comment by mahotilo** [comment]
Wow!!!. It is awesome! 
It's not X-mas now, but Santa is here :)
I'll test it intensively, but as for now it works like I dreamed.
