### ISSUE TITLE
We got 2 CVEs to check

### ISSUE THREAD

**Issue by juek** [Typesetter/Typesetter#238]
CSRF [CVE-2018-6888](https://www.exploit-db.com/exploits/44029/)
Host Header Injection [CVE-2018-6889](https://www.exploit-db.com/exploits/44028/)

**Comment by juek** [comment]
For the CSRF: I cannot confirm this one. Even if logged-in, the forged request will not be processed because of the invalid post nonce. Refuses to add the user showing a "XSS Verification Parameter Mismatch" error.

**Comment by juek** [comment]
However, any insights are welcome.

**Comment by oyejorge** [comment]
**CSRF CVE-2018-6888**

From the exploit description:
> To Mitigate CSRF vulnerability, it is recommeded to enforce security tokens such as anti csrf tokens​

Typesetter already has a CSRF token, the author of the exploit just didn't see it because it's not labeled "CSRF". In fact, they copied the token (that was valid for their session) into their example:

>  &lt;input type="hidden" name="verified" value="475f10871b08f44c20dab5bc2cb55d17946e6c98fa8abf28c64a5a9dab0ee2e122fefcc29cae9cc2e48daf564bfe55665e26b2b2174dee14e83c5e6974cf3218" />

**Host Header Injection CVE-2018-6889**
I'm not seeing how this would work. Someone could fabricate a request like so:
> POST https://example.com/Admin HTTP/1.1
> Host: evil.com

With such a request, the Host header will have a value of "evil.com" instead of "example.com". Typesetter, however, doesn't use the value of the "Host" header and uses $_SERVER['SERVER_NAME'] exclusively. In php, it becomes a problem when $_SERVER['HTTP_HOST'] is used. [More Info](https://stackoverflow.com/questions/2297403/what-is-the-difference-between-http-host-and-server-name-in-php/2297421#2297421)

**Comment by juek** [comment]
I found the original blog post [here](https://securitywarrior9.blogspot.com/2018/02/host-header-injection-type-setter-cms-51.html) with 2 screenshots. 

Quote from php.net

> 'SERVER_NAME'
> The name of the server host under which the current script is executing. If the script is running on a virtual host, this will be the value defined for that virtual host.
> 
> Note: Under Apache 2, you must set UseCanonicalName = On and ServerName. Otherwise, this value reflects the hostname supplied by the client, which can be spoofed. It is not safe to rely on this value in security-dependent contexts. 

With Apache 2 UseCanonicalName seems to be Off [by default](https://httpd.apache.org/docs/2.4/mod/core.html#usecanonicalname)
