### ISSUE TITLE
codemirror

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#252]
You gave me for theme_content_outer.js
 the hint
 var codeMirrorConfig = {
	mode : 'text/x-less',
	lineWrapping : false,
	lineNumbers : true
};
The lineWrapping : false, has no effect (set to 'true').
You use the old version of codemirror in the master (now 5.1.1beta1). Is there any chance that You use the new version, because the ckeditor-plugin uses the new version and both can mix up. ( i updated it on my cms, and the layouteditor functions)

**Comment by juek** [comment]
> both can mix up

why should they mix up?

**Comment by juek** [comment]
Of course we could update codemirror, but the current implementation does what it's supposed to do–namely robust Css/Scss/LESS syntax highlighting, solely in Layout Editor. 
Version 5.37 is ~370 kB while current 5.10 is ~210 kB. So, as long as we do not need newer features in Layout Editor, IMO there is no need to update it. We would only needlessly load additional 150 kB of JavaScript.

**Comment by gtbu** [comment]
I do not want to urge You to update, but there myght be extensions in the future.
The renamed Codemirror.min from beyond  is 
https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.10.0/codemirror.min.js is 172 KB
https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.37.0/codemirror.min.js   150 KB , as Zip 53 KB).
https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.37.0/codemirror.min.css  5.8 KB
Most administrators will have mod-deflate activated.
................................................................................................................................................................................
Another question about ckeditor : There is the possibility of using js-namespaces (and jquery.noconflict) and require.js. Are there any namespaces in context with ckeditor in Typesetter, and have there been tests with js-namespace and plugins ? There must be  a real reason why some plugins function within a pure html-embedding of ckeditor and not in many CMSses.

**Comment by juek** [comment]
JavaScript does not have declared namespaces like e.g. PHP. Everything 'namespaced' in JS is either part of a function or an object. 
Every reasonably well written JS component will do it. It's a fundamental principle you will find everywhere. jQuery's namespace is $. CKEditor (even multiple instances) live entirely in the global CKEDITOR object. On the other hand, invoking codemirror will create a new instance of the CodeMirror object. 

> Are there any namespaces in context with ckeditor in Typesetter, 

Nothing special. When loaded, there is the global CKEDITOR object. 

> and have there been tests with js-namespace and plugins?

Sorry, but the question doesn't really make sense. CKEditor plugins either directly modify (parts of) the CKEDITOR object or execute as a immediately invoked function expression (iife), which will subsequently write to the CKEDITOR object somehow. They normally don't use custom 'namespaces'. (Of course, plugins like CKEditor-CodeMirror will create a CodeMirror instance). Loading and execution is done by CKEditor based on its plugin configuration. You would really have a hard time to change this architecture.

**Comment by juek** [comment]
> I do not want to urge You to update, but there might be extensions in the future.

Well then let's update it and test it when they're needed. Again, CodeMirror in Typesetter serves a distinct specific purpose and it currently does it well, without issues. So why change a winning team.

**Comment by gtbu** [comment]
Independent of the necessety of an update does the layouteditor save its content to somewhere, and the systembackup dos not include its content! A solution would be to save an additional layout.(s)css in the respective themefolder.
------------------------
Another reason for the 'necessity' of an update of codemirror is also a future plugin, which allows to edit the templates and the styles(which would then overrite  the old codemirror).

**Comment by juek** [comment]
> Independent of the necessety of an update does the layouteditor save its content to somewhere, 

The Css/Scss/LESS of layouts will be saved to /data/_layouts/[random dir names]. 
Other layout data will be saved to /data/_site/config.php and /data/_site/pages.php

> and the systembackup does not include its content!

This was fixed with [this commit](https://github.com/Typesetter/Typesetter/commit/bd56fbac71c1989274b1ebfeef70aa300ecb6990)

> A solution would be to save an additional layout.(s)css in the respective themefolder.

Typesetter will not write to the /themes folder. Everything done by admins will be stored in /data

> Another reason for the 'necessity' of an update of codemirror is also a future plugin, which allows to edit the templates and the styles(which would then overrite the old codemirror).

CodeMirror in /include/thridparty/codemirror is (at least up to now) not a loadable Typesetter component, but will only be loaded with Layout Editor together with an appropriate configuration. 
CKEditor CodeMirror plugin(s) will use their own bundled CodeMirror version. 
For any other custom plugins, such as a template editor, feel free to bundle it with a suitable codemirror version and possible additional components (e.g. for syntax highlighting). 

If you're planning a template editor, please bear in mind that one of Typesetter's core security concepts is that admins are *not* able to edit executable scripts. The possibility to edit e.g. template.php will break this concept. We can discuss this in a different thread/issue if you wish.

**Comment by gtbu** [comment]
There are surely ways to edit php-files in spite.... At the Moment i am more learning, and i do not want to hack the system . 

But what i would change immediately in Typesetter is the $ of jquery in the CMS like
<script src="scripts/jquery.1.10.js"></script>
<script src="scripts/jquery.2.14.js"></script>
<script>
	var jt = jQuery.noConflict(true);  /for use in Typesetter
</script>
So that the dashborad runs in its own virtual Namespace. That is of course a lof of work but it avoids  lots of unnecessary conflict.

**Comment by juek** [comment]
jQuery.noConflict is only needed in cases other JS libraries (like Prototype or MooTools) are using the global $ variable. Since jQuery is not only a core component of Typesetter but aslo the second most popular JS libary in the world (after React.js), any additionally used JS components/libs have to adapt to that fact. Nobody should write JS code conflicting with jQuery anymore nowadays - that's truly begging for trouble, not only with Typesetter.

> i would change immediately in Typesetter is the $ of jquery in the CMS

No. You would have to rewrite Bootstrap, Colorbox, finder… well, actually almost every JavaScript that comes with Typesetter. It would also break almost every existing Typesetter plugin. With Typesetter, $ is jQuery. Period.

> <script src="scripts/jquery.1.10.js"></script> <script src="scripts/jquery.2.14.js"></script>

Don't! It not only doesn't make sense to load multiple/additional jQuery versions. Typesetter already loads jQuery (currently 1.11.3) by default at an early stage. Loading an additional jQuery script later (e.g. in template.php or via addons) will certainly cause strange behavior because it will overwrite the already  existing jQuery, thereby all already initiated functions, event handlers, etc. 

If your scripts conflict with jQuery, you will have to resolve them–not Typesetter.

**Comment by gtbu** [comment]
I can really not understand what You say : 
An additional declaration var $jt = jQuery.noConflict(true); creates an ADDITIONAL virtual namespace and does not remove the $ namespace. It puts the CMS in a namespace and avoids conflicts.
I made this for test with $jt = jQuery.noConflict(removeAll);  and appended it at the end of jquery.js and had no complications. But it is of course Your CMS.
You should see that developers of templates are not necessary professionals - do You want to select only professionals who might prefer wordpress ? 
People who use materialize.css (not MDL) use jquery 2. The problems is that errors can eventually just make the system slower, and the firefox-Javascript console can be very difficult. I have for example a ckeditor- plugin which installs without complication (dependencies installed before) and stays grayed out in ckeditor. In github i saw commentaries to uninstallable bootstrap-plugins to embed them for scratch - additional installation in 4.62 is only possible with 2 from 8 -- in 4.7 not at all. 49/5000
I'm currently trying to cope with these problems.

**Comment by juek** [comment]
It looks to me as what you are doing is to map $ from the most previously loaded custom jQuery to the new global $jt variable, thereby making Typesetter's built-in jQuery (1.11.3) re-accessible via $ (passing true as argument to the noConflict method will even do the same to the 'jQuery' variable).
This way, you will have an additional jQuery version, e.g. ver 2.14, 'running as' $jt. Everything still using the global $ or jQuery variables will use Typesetter's native jQuery 1.11.3. Although this will work, it will not change Typesetter's way of using jQuery at all and will not 'virtualize' or 'sandbox' anything. You only get an additional jQuery 2.14 to use via $jt, with the huge drawback of loading 2 large similar JS libraries. I'd rather go for a recent jQuer version and use jquery-migrate to care for backwards compatibility is nuch a case.
If your intention is to run all native Typesetter JavaScript inside the $jt 'namespace', you would have to rewrite most of the CMS, thirdparty and addons' code. When *not* passing true to noConflict, similar could – theoretically – be achieved by wrapping everything in an iife by passing the original jQuery as $, like (function($){ /* all Typesetter JS referencing $ goes here */ })(jQuery); But that's not feasible, because Typesetter will load and call JS in various different ways.

> But it is of course Your CMS. 

It is not. I'm just currently maintaining the main repository. Josh S. mostly made it. Everyone may fork it, it's GPL.

> You should see that developers of templates are not necessary professionals.

Every CMS and framework comes with some preconditions and standards to be met to make own code work. There are quite some simpler ones than Typesetter, but most are way more complex. I don't know any CMS that allows to do everything. 

> I have for example a ckeditor- plugin which installs without complication (dependencies installed before) and stays grayed out in ckeditor.

There are plenty of plugins with conflicts or - even undocumented - dependencies. Sometimes they can be fixed rather easily, sometimes we just simply cannot use them. 
Typesetter's way of loading, caching, hibernating and 'reawakening' editor instances during single editing sessions is a quite special technique and it will prevent certain functional concepts or make them at least very hard to handle. I admit, that it's extemely difficult to debug such stuff. 
Simple namespacing will not help e.g. in cases where a CKEditor plugin expects some dom ready or window load events firing in order to (re-)scan and gather updated information from the DOM, when a hibernated CKEditor instance is reawakened. Expected but not firing events will not throw errors. But that's just one example.

**Comment by juek** [comment]
It's inevitable that upcoming Typesetter modernization steps will update jQuery and other libraries/components to more recent versions and we will certainly move to PHP 5.6+ (if not 7), maybe even CKEditor 5. Many existing websites will not be able to upgrade to such a new Typesetter version because it will drop support for *lots* of legacy components and plugins. So, it's a hard decision what to keep and what to sacrifice.

**Comment by gtbu** [comment]
This was a long discussion with a misunderstnding :  An appended  var $jt =....  ,  which is then used instead of $ creates the possibility for Typesetter (or other software using this variable) to run in the virtual namespace 'jt' , and so it is transparent for other processes using just $ (which may still have conflicts with other JS using just the $.
(Another problem solvable with noConflict is the use of 2 versions of jquery).
...............................................................
I had a look at ckeditor 5 and heared, that it saves in a different format. I read warnings in the web not to open a site with ckeditor 5 which was saved with ckeditor 4.  My interest was at the moment to find the reason why many plugins in a html-embeddedversion do not run in a cms - not only in not in Typesetter.
(But You will have to work and i am already in pension and just waste Your time.) ---------------
Many german providers are giving php 5.x up, because it is much faster, and the inner datatraffic in the servers is also about 50 % - so they need less computerpower for their shared web and have less costs....!
