### ISSUE TITLE
Cssmin update

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#255]
In include/thirdparty is a cssmin_1.0.php which is quite old but small (but the php-server executes it...) . 

An updated version of the author is  at https://github.com/JoeScylla/cssmin/tree/master/src  (v 3.01)

**An updated version for php 7.2** with bugfixes is at  https://github.com/natxet/CssMin/releases  (v3.06)

I exchanged the old 1.0 with this version 3.06 (also changed the name) with php 5.6 and php 7.1 and had no problems.

So i think that the old version should be replaced  in the master.

**Comment by juek** [comment]
Ver. 1 is much simpler than ver. 3 in almost any aspect, but I didn't yet have any issues with ver. 1. 
Current version 3.06 has still bugs that break certain rules, which I believe ver. 1 doesn't have.
Ver 3 also has a huge footprint (160 kB) in comparions to v. 1 (2 kB).

So the questions are: 

- Did you have any issues with v. 1?
- Have you tested ver 3.06 for PHP 5.3 compatibility (which we still need)?
- Did you compare memory consumption and performance - both are crucial factors?
- What would be the benefits of using ver. 3?

**Comment by gtbu** [comment]
No - i just thought of the new Typesetter beta and of php 7.2 , which many bigger german providers offer. I cant test under php 5.3 (which is unsafe and slow - and who uses it really) - only on 5.6 .
The footprint is no argument, since only the php-server executes it  for a short moment.
But I think the author had reasons for further developments - and why should 1.0 have no bugs ?  
I have no means to test it so deep. 
The css-size does not really influnce me since i use mod_deflate.
 This is more a proposal. Perhaps it has a better compression.

**Comment by juek** [comment]
> php 7.2 , which many bigger german providers offer. 

Albeit not yet tested, PHP 7.2 shouldn't be an issue with the current ver. 1 implementation. I believe compatibility issues only arise from newer versions, which are much more complex.

> The footprint is no argument, since only the php-server executes it for a short moment.

Basically true, but a larger script also normally uses more resources.

> I think the author had reasons for further developments like better compression and compatibility

Certainly, but what I have seen by quickly looking up the code, the newer version does things like verndor prefixing/removal and other stuff we don't need – or I'd not prefer to use since Scss/LESS is way more versatile in this regard.

> and why should 1.0 have no bugs just because it is so simple - it can be too simple ?

It might have bugs but I haven't encountered one yet. Less complexity is always the better chioce.

> I have no means to test it so deep. 

The new [minifyjs implementation](https://github.com/Typesetter/Typesetter/blob/c5acd8048912f1c6cc5535fbd833aa7001605f1a/include/tool/Output/Combine.php#L668) has some code to measure execution time and memory consumption.

> The css-size does not really influnce me since i use mod_deflate.

cssmin was implemented (by [mahotilo](https://github.com/mahotilo)) to address optimzations demanded by Google Pagespeed Insights and other SEO tools and minification might impact page ranking to a certain degree in the future.
mod_deflate and mod_gzip will compress the css uppon transmission but it will, for example, not remove comments.

**Comment by juek** [comment]
I'm not entirely against updating cssmin, so I'll leave this up to @mahotilo. Lena, are you reading along?

**Comment by mahotilo** [comment]
@juek  and @gtbu 

Yes Google Page Speed is my headache:)

Now Google Page Speed is fully satisfied with the level of TS css minification. So there is no real need to improve something.

Moreover, along with minification, we have one more estimation parameter in Page Speed Insight. This is the time from the request to the recieving the first lines of the html code.

On cheap shared hosting this parameter is not high (2-3 times more then recomended 0,2s). The strength of TS - its light and speed. If the new version of the cssmin processes CSS for longer then current 1.0, we can slightly win in compression, but lose a lot in the request time!

----
By the way, Juergen. It's a pity that similar logins have misled you, but mahotilo and lena.mahotlo are two different users. Just my first name is too long to add it to my login :) (Hint, this is the son of empress Helena (Lena). My hobby is to help lena.mahotlo with CMSs insides, but I'm just a CMS-mechanic :) (keine Mechanikerin)

**Comment by juek** [comment]
> I'm just a CMS-mechanic :) (keine Mechanikerin)

:-) Gotcha!

> [...] but lose a lot in the request time!

Shouldn't be too much of an issue, since cssmin will only step in when a new cache is written. 
But I agree with you – let's keep it lean.

**Comment by juek** [comment]
> php 5.3 (which is unsafe and slow - and who uses it really) 

FYI: https://w3techs.com/technologies/details/pl-php/5/all
