### ISSUE TITLE
Backup of manaually installed ckeditor addons

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#261]
I had a typesetter 5.1 installation with a strange problem that something had put the topsite 'Start' to 'private' - but the rest of the site was ok.

So i decided to make a backup and imported it into a new master51b1-installation. 
But I had 4.57 instead of previous 4.73  and the previously manually installed ckeditor-addons were not there. 
Is the ckeditor 4.57 protected ?
Then i installed the ckeditor 4.62 update which was ok.

**Comment by juek** [comment]
> But I had 4.57 instead of previous 4.73 [...] Is the ckeditor 4.57 protected ?

The core system files (everything in /include) will not be exported to the backup.

> The previously manually installed ckeditor-addons were not there.

True. Should be fixed with [this commit](https://github.com/Typesetter/Typesetter/commit/f3aa8404e1ab529b9db8db62509538fd07f0070a)

**Comment by gtbu** [comment]
I propose to complete the above commit with :  $add_dirs[] = $dataDir.'  /include/thirdparty/ckeditor_34 (of course not $dataDir)  
There is still that a manually restored style-lay.css in the _exports directory does not appear in the layout editor but must be filled into the layouteditor manually. 
I added a line  to the layout of the (unused) h5-template and got in /data/_layouts/ega6i7w a custom.css which is quite unintuitive to find - it would be better to add h5.md or similar or open instead a directory ega6i7w-h5 .

**Comment by juek** [comment]
> I propose to complete the above commit with : $add_dirs[] = $dataDir.' /include/thirdparty/ckeditor_34

Sorry, but the export function is meant for data back-up and content migration purposes and shall not touch system components. It would mess-up the core when migrating a site to a different cms version.
Your CKeditor update plugin will be archived as well. If I rember the code correctly, you can simply re-apply the patch from there, can't you?

> I added a line to the layout of the (unused) h5-template and got the content in a new /data/_layouts/ega6i7w a custom.css which is quite unintuitive to find.

The content of the /data/_layouts/ subdirectories is not meant to be edited manually - it will change with edits in Layout Editor. Depending on the web/FTP server configuration, together with the default settings in /gpconfig.php, (S)FTP users normally won't even have write permissions to these files. If you want to edit theme stylesheets at file system level, download the theme and unpack the contents of the ZIP archive to the /addons directory (AKA developer installation). All edits there will be safe from changes done via admin UI and even theme uninstalls. Typesetter systematically separates between admin UI and filesystem access level (or let's call it developer vs. admin access level). We will keep it this way–it's a good security measure.

> [..] after i added code to the unused Bootswatch - Flatly in the layout editor, which had alread code in the layout editor, nor additional directory was created...

Layout data will be saved the same way for all themes. It will not be stored in a different location, so if you can see the code changes in Layout Editor, it's data will be in a /data/_layouts/[rand_dirname] directory. 

> (and i cant find the change anywhere - i see the date of change).

If the file creation/modification date is off, check your server's date/time settings. But I'd rather believe it's the UTC time that servers use, that causes the confusion.

> For a time i will add an outcommented line with the templatename in the Layouteditor and add the obove commit to the 5.1 installation

I'll be happy to merge it. But please mind to sanitize and normalize the theme name in order to make it filesystem compatible. Theme names may contain characters that don't qualify for directory names. If you're planning to even add the layout name, also bear in mind that this string can be set by admins, therefore it might even pose a security risk, if not properly sanitized.
