### ISSUE TITLE
XSS via svg fileupload: Typesetter 5.1

### ISSUE THREAD

**Issue by security-breachlock** [Typesetter/Typesetter#290]
Affected software: Typesetter 5.1

Type of vulnerability: XSS via svg fileupload
 
URL: https://www.typesettercms.com/
 
Discovered by: BreachLock

Website: https://www.breachlock.com

Author: Balvinder Singh

Description: SVG files can contain Javascript in <script> tags. Browsers are smart enough to ignore scripts embedded in SVG files included via IMG tags. However, a direct request for an SVG file will result in the scripts being executed. 
So an embedded SVG as an attachment in an issue or avatar does not execute the code, but if a user clicks on the attachment the code will execute.

Proof of concept:
Step1: Login into the Typesetter using the admin role.
Step2: In the content, section choose file upload and upload a malicious SVG file.
Step3: Now open that file which was saved as 1.svg the below output will be shown.
URL Where XSS got executed- Localhost/Typesetter/data/_uploaded/1.svg

![typesetter_svg](https://user-images.githubusercontent.com/41563984/43941993-dce84b0c-9c93-11e8-8187-edcc6f1d1faf.JPG)

VulnerableURL: http://localhost/Typesetter/index.php/Admin/Uploaded

**Comment by juek** [comment]
As mentioned [here](https://github.com/Typesetter/Typesetter/issues/291), Typesetter admins are given responsibility for client-side scripting – they may even upload .js files or .html files containing script code.
Typesetter also allowed to upload and embed flash/swf all along, which must also be considered potentially hazardous.

But I agree with you that SVGs is a special case because even experienced admins may take them for sole vector images and are unaware or simply forget about the possibility of malicious scripts in them. 

We should probably issue a warning message about uploading SVGs from untrusted sources.

**Comment by security-provensec** [comment]
Hi Juek,

Thanks for your positive response,

Did you use CVE ID to track these bugs?

Looking forward to hearing from you.

**Comment by security-provensec** [comment]
Hi,

Any updates please.

**Comment by juek** [comment]
As said, we will warn admins from uploading untrusted SVGs with the next release of Typesetter but we do not consider it a security vulnerability because of our admins policy allowing client-side scripting. We're not going to change that.

If Mitre still gives you a CVE for it, so be it. I would not.

**Comment by juek** [comment]
SVG upload is now implemented as configuration value [with this commit](https://github.com/Typesetter/Typesetter/commit/02e2e03a211819ea8ec985479e4e22aa1fdf63e8)
