### ISSUE TITLE
Non-Persistent or Type-II XSS : Typesetter 5.1

### ISSUE THREAD

**Issue by security-provensec** [Typesetter/Typesetter#292]
Affected software: Typesetter 5.1

Type of vulnerability: Non-Persistent or Type-II XSS

URL: : https://www.typesettercms.com/

Discovered by: Provensec

Website: https://www.provensec.com

Author: Balvinder Singh

Description: Reflected attacks are those where the injected script is reflected off the web server, such as in an error message, search result, or any other response that includes some or all of the input sent to the server as part of the request. Reflected attacks are delivered to victims via another route, such as in an e-mail message, or on some other website. When a user is tricked into clicking on a malicious link, submitting a specially crafted form, or even just browsing to a malicious site, the injected code travels to the vulnerable website, which reflects the attack back to the user’s browser. The browser then executes the code because it came from a "trusted" server. Reflected XSS is also sometimes referred to as Non-Persistent or Type-II XSS.

Proof of concept:

Step1: Login to the Typesetter using the user role.

Step2: In the content section, create a new page. Here the LABEL parameter is vulnerable.

![typesetter_re](https://user-images.githubusercontent.com/41563984/44022770-3a2558a4-9f06-11e8-8bf4-310bbaf5c20a.JPG)

Step3: Enter the malicious code in the label field and the javascript got executed successfully.

![ref_type](https://user-images.githubusercontent.com/41563984/44022819-5e532404-9f06-11e8-8f1d-f753282405ee.JPG)

Vulnerable URL: http://localhost/Typesetter/Typesetter/index.php/Admin

**Comment by gtbu** [comment]
1. There is the possibility to limit the maximum url-length.
2. In another small system which i patched 
http://net.square7.ch/XH1610/XH1610clean-0.5/Download (developement is stopped)
i used a filter against attacts - until today uncracked.

**Comment by juek** [comment]
This 'security issue' is based on a wrong assumtion: there is no 'user role'. 

While we may restrict account access to certain resources, a Typesetter 'user' – without any editing permissions doesn't make much sense. 

E.g. in this particular case: If an admin has permissions to create a page, he may also edit this page. 
If he then wants to insert (legit, stupid or malicious) JavaScript code, he then may simply insert a <script> block with arbitrary code into the content. Typesetter admins don't need filter evasion trickery to execute custom JavaScript. This is by design – we're not planning to change that.

Typesetter is *not* a community platform with untrusted member accounts. 
Admins are considered responsible and trusted.

**Comment by gtbu** [comment]
What i wanted also to say with the above link, which contains a filter-code, is that it should be possible to include such a php-code into the head of a template and also add 'prompt' and other strings and also limit the length of the filename with such a flexible filter, which can also be implemented as a plugin (if not in the CMS).
