### ISSUE TITLE
XSS on the Typesetter 5.1.1

### ISSUE THREAD

**Issue by Hu3sky** [Typesetter/Typesetter#293]
The XSS is on the page http://127.0.0.1/cms/Typesetter-master/Admin/Missing
edit the 404 page
![tim 20180824211249](https://user-images.githubusercontent.com/37403964/44586580-c9823000-a7e2-11e8-91d5-5cd7be79678b.png)
then click the Source,and fill the payload `<svg/onload=alert(1)>` in it.
![tim 20180824211122](https://user-images.githubusercontent.com/37403964/44586604-def75a00-a7e2-11e8-8ed8-e05e47650104.png)
Lastly,go to the page which HTTP Status Code is 404
For example , http://127.0.0.1/cms/Typesetter-master/asfdsfdsgdfgfd
![tim 20180824211145](https://user-images.githubusercontent.com/37403964/44586663-17973380-a7e3-11e8-911d-ab21b3c68098.png)

**Comment by juek** [comment]
Typesetter admins may use JavaScript by design. Instead of using filter evasion tricks, you can even simply add

```
<script>
  alert("Welcome to JavaScript");
</script>
```

**Comment by Hu3sky** [comment]
but it also can attack the cookie,it's dangerous

**Comment by juek** [comment]
> but it also can attack the cookie

You could also directly disclose your login credentials. 
Both things you certainly wouldn't want to.

**Comment by LorenzoAncora** [comment]
**This is not a vulnerability**: by-design CMS administrators **must** be able to inject javascript.

Administrators are responsible for the users' good UX: in order to guarantee a good user experience they must be able to add markups and scripts.

JavaScript is a Turing-complete language and therefore it is impossible to block all malicious code: administrators are responsible for user security and for the security of their administrative accounts, as in any other website.

@juek @oyejorge I suggest to close this issue (labels: `won't fix` + `invalid`).
