### ISSUE TITLE
problem since this Vers.5.1

### ISSUE THREAD

**Issue by Knuzen** [Typesetter/Typesetter#308]

**Comment by mahotilo** [comment]
??? No description provided.

**Comment by Knuzen** [comment]
Dear Josh

I used TYpesetter Vers.5.01 sind 2016 and everything works fine.

Now with the last Vers. 5.1 a lot of mystic errors appear.
1. Automatic update hangs !!! don't work
2. addon data could not be fetched

For a better work and turn arround, I want to download 5.01 (or similar)
Maybe I get a hint.

**Comment by mahotilo** [comment]
You can find old releases here
https://github.com/Typesetter/Typesetter/releases

**Comment by Knuzen** [comment]
@mahotilo: Thanks for this hint. I am glad.
But at least, this will not solve the new problems with TS 5.1, you agree ?

**Comment by mahotilo** [comment]
We do have problems with automatic updates from 5.01 to 5.0.3 and 5.1. You can try to directly replace dir `include` on your server via ftp to install new version.

**Comment by mahotilo** [comment]
> 2\. addon data could not be fetched
From time to time anyone may get such problems. Often this is due to the hosting settings. Can you give a more precise description of problems you meet?

**Comment by Knuzen** [comment]
for a better understanding: You mean to exchange the folder /include of verse 5.1 with the old folder /include 5.03 and everything works fine with the old content. I do not want to make mistakes, to destroy my whole content of the website.

My problem is: addon data could not be fetched. In Vers.5.03 it works fine, now at 5.1 I get a error.
Is this precise enough ?

**Comment by mahotilo** [comment]
1. Please read this for more detailed instruction
https://www.typesettercms.com/Forum?show=t2433 
https://www.typesettercms.com/Docs/Upgrading

**Comment by Knuzen** [comment]
TNX, my friend. I will try this.
Bye for now.

**Comment by Knuzen** [comment]
@mahotilo 
The same trouble.
Plugins »ManageAvailable (2)Search
Sorry, the addon data could not be fetched from TypesetterCMS.com. More Info...
View search results on TypesetterCMS.com
First I change the update.php, -> makes error
Then I changed /include -> error

![bild 2019-02-16 0001](https://user-images.githubusercontent.com/10711934/52899686-11f83480-31ed-11e9-9c3d-89bb609856d6.jpg)

I'll better use TS 5.03 instead of wasting time, or do you have a better idea ?

**Comment by mahotilo** [comment]
1. You just should have got a site with a new version of CMS when you replaced /include dir with new one from downloaded [Typesetter-5.1.zip](https://github.com/Typesetter/Typesetter/releases/download/v5.1/Typesetter-5.1.zip). The update procedure is not needed.

2. Do you have the same checking before open typesettercms.com? Maybe this protection is source of problem? Can you download addons on your TS-5.01 system?
![image](https://user-images.githubusercontent.com/14929385/52900226-04967680-31fc-11e9-91e8-d472801618f6.png)
In any case you can add addons to CMS through direct unzipping it to /addons  dir.

**Comment by gtbu** [comment]
There have been many changes between Typestter 5.01 and the momentary master.  Some plugins and themes are incompatible with 5.01.

2 solutions have been discussed at  https://www.typesettercms.com/Forum?show=t2708 

At the moment the provider of typesetter.com has a DDos-Filter installed, because of hacker-attacs , which also blocks the search for new themes and plugins. The only solution is a patch of the code which can only be done by the developer. or to seek another provider. I have alread proposed that.

**Comment by Knuzen** [comment]
OK Fellows, thanks for every answer/hints, but I'm just confused what to do, since I need a solution for two Websites.
All discussed hints don't work really satisfactory, as in the beginning with GpEasy.
I have a lot of content from some websites, which must be ported, or I have to do it by hand. Hint for automated porting are stupid and don't work really good. Not from 5.03 -> 5.1.?
I don't understand, why a version 5.1 with errors/mistakes could be as the final download at typesetter.com. 
This is not professional.

**Comment by mahotilo** [comment]
It is always hard to keep high development rate and quality at same time. As for me, TS deal with this dilemma good enough. This is an open source project, and since version 5 is driven mainly by the community. So now it is not about professionalism, but about the goodwill and time of the contributors (in particular, Juergen @juek).

**Comment by juek** [comment]
Hi folks - I'm sorry for being too busy at the moment to participate in the current discussions in detail.

@Knuzen and all: The current issues with inline updating the CMS and installing addons (from within Typesetter) are due to cloudflare's DDos protection. Although I don't know if it was acticated automatically or by hand, it prevents proper communication of CMS installations with the backend on typesettercms.com. As long as it is active we need to install updates and addons manually.

@gtbu: I'm not aware of any addon incompatibilities between Typesetter 5.0.1, 5.1 and the current 5.1.1-b1. A transition from 5.0.1 to  5.1.1-b1 shouldn't cause any issues. The latest architectural changes in the CMS that would cause incompatibilities were in the transition from last gpEasy CMS (4.5) to Typesetter CMS(4.6/ 5.0)

**Comment by gtbu** [comment]
I made a whios for typesettercms.com https://www.united-domains.de/whois-suche/  and at
https://www.tucowsdomains.com/whois-result/  (the registrar)
It says : Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
Domain Status: clientUpdateProhibited https://icann.org/epp#clientUpdateProhibited

Perhaps You can add https to typesettercms.com or a Ddos - Filter (as there are several at github)

**Comment by LorenzoAncora** [comment]
> [...] It says : Domain Status: **clientTransferProhibited** https://icann.org/epp#clientTransferProhibited
Domain Status: **clientUpdateProhibited** https://icann.org/epp#clientUpdateProhibited [...]

@gtbu this is not an error, these are correct parameters.
Those DNS security measures must be disabled only during a change of registrar (to allow the transfer) and then be enabled again. Without them, an attacker could hijack users' network traffic.
**Never leave these safety measures disabled.**

> Perhaps You can **add https to typesettercms.com** or a **Ddos - Filter** [...]

1. **The website is already accessible via HTTPS**, only that it is (correctly) set to not enforce encryption. However, the certificate in use (by Comodo) does not have a good reputation and it would be a good idea to use a different CA. However **you can visit https://typesettercms.com to view the site via a secure connection**.
2. The DDoS attack does not exploit a vulnerability in the target machine, but merely saturates the victim's network and calculation resources so that the service is inaccessible to other users. For this reason **there can not be a "DDoS filter", there are only mitigations**. In this case CloudFlare acts as one of these mitigation measures, despite creating other problems.

**Comment by FAFDK** [comment]
Any progress on this problem? - to not being able to fetch addons and themes through the UI?
----------
Backtrace
--
File | /include/admin/Addon/Install.php
Line | 363
Class | gp\admin\Addon\Install
Function | ParseResponse

Redir | 0
FailedMethods | stream,
NotSupported |  
stream | no handle
lang_key | Sorry, data not fetched

PHP Version | 7.2.14-1+0~20190113100742.14+stretch~1.gbpd83c69
CMS Version | 5.1
index.php Rewrite | True
Server Software | Apache/2.4.25 (Debian) mod_fcgid/2.3.9 OpenSSL/1.0.2q

**Comment by gtbu** [comment]
Now the filter is off .
If You habe problems with self-provider installation of Typesetter5.1 - evtl. this can help You

https://www.linuxhelp.com/how-to-install-typesetter-cms-5-1-on-ubuntu-18-04-1
