### ISSUE TITLE
PHP 7 : Recovery password Not Working

### ISSUE THREAD

**Issue by loorlab** [Typesetter/Typesetter#311]
Hi friends, We updated our instance to PHP 7.2 and could not enter as administrators.

We try to recover the password and it shows us the following: "There was an error, please try again."

Is there possibility of compatibility with PHP7?

Thanks !

**Comment by gtbu** [comment]
Which version of Typesetter do You use ? I have 3 Sites with php 7.2 - can You delete the browser cache - what happens if You switch back to 7.0 or other.

**Comment by loorlab** [comment]
@gtbu Hi, Our Typesetter is version 5.1 The site already tells me that it sends the mail, but it does not arrive, possibly it is an advanced configuration of STMP and AWS .

**Comment by gtbu** [comment]
no - its a bug - see previous issue #307

**Comment by loorlab** [comment]
> 
> 
> no - its a bug - see previous issue #307

Thanks !

**Comment by gtbu** [comment]
Sorry i did misunderstand You 👍 
The reason may in Your case be a missing port for email - which the provider inhibited because of spawn ( as at 000webhostapp.com ) : - if not - a functioning configuration for You

First Line Recipient Address *   --> Your email
From Address  -- > AutomatedSender@yourdomain.com
From Name --> AutomatedSender
Require Contact Fields -->  subject and message 👍

**Comment by gtbu** [comment]
Sorry i did misunderstand You .....
The reason may in Your case be a missing port for email - which the provider inhibited because of spawn ( as at 000webhostapp.com ) : - if not - a functioning configuration for You

First Line Recipient Address *   --> Your email
From Address  -- > AutomatedSender@yourdomain.com
From Name --> AutomatedSender
Require Contact Fields -->  subject and message 

P.S. The Problem with not functioning lost password  exists only for users who use password_hash instead of sha512.

**Comment by juek** [comment]
@loorlab 
> Hi, Our Typesetter is version 5.1 The site already tells me that it sends the mail, but it does not arrive

It's always a good advice to check if sending mail works, e.g. using the contact form. From my experience, using the 'phpmail' option in Configuration -> Settings only works in 60-70%. It depends A) on the host configuration, B) possible blacklisting but also C) on the SPAM filter settings of the receiving mailserver.

Most reliable setting is using SMTPauth in combination with a real existing mailbox as sender address (e.g. noreply@yourhost.com). This works in almost every case. E-mail from existing mailboxes, sent via SMTP, do get the lowest spamscore, if any.

**Comment by juek** [comment]
For the [mentioned bug](https://github.com/Typesetter/Typesetter/issues/307): I'm currently not able to reproduce it using PHP 7.3 but I will investigate further…

**Comment by juek** [comment]
Seems I got it working with [this commit](https://github.com/Typesetter/Typesetter/commit/5fd8ac1a4c94d29d5997e2ac05d9e48bf4bea57f)

Please check.

**Comment by gtbu** [comment]
Sorry - but at php 5.6 the sen password_hush -  password is still incorrect  (exchanged login.php competely)

**Comment by loorlab** [comment]
@juek & @gtbu Thanks !

We have problems with AWS regarding "sendmail" but we tested the following:

1) replace login.php und tool.php  and not working
2)  We activate Typesetter debug to True and /kb/Admin/Configuration display the following :

Deprecated (8192)
__autoload() is deprecated, use spl_autoload_register() instead
    in: /path/kb/include/thirdparty/PHPMailer/PHPMailerAutoload.php
    on line: 45
    Request: /kb/Admin/Configuration
    Method: GET

array(
   [0] => array(
      [file] => (string)/path/kb/include/common.php
      [line] => (integer)503
      [function] => (string)require_once
   )
   [1] => array(
      [file] => (string)/path/kb/include/tool/Emailer.php
      [line] => (integer)7
      [function] => (string)includeFile
      [args] => (string)array(1)
   )
   [2] => array(
      [file] => (string)/path/kb/include/tool.php
      [line] => (integer)230
      [args] => (string)array(1)
      [function] => (string)include_once
   )
   [3] => array(
      [function] => (string)Autoload
      [class] => (string)gp\tool
      [type] => (string)::
      [args] => (string)array(1)
   )
   [4] => array(
      [file] => (string)/path/kb/include/admin/Configuration.php
      [line] => (integer)169
      [function] => (string)spl_autoload_call
      [args] => (string)array(1)
   )
)

We are temporarily resolving the sending of emails with Mandrill, we would like to know if it is possible to configure Mandrill as the basis for sending default Typesetter notifications.

Thanks

**Comment by juek** [comment]
> Deprecated (8192)
> __autoload() is deprecated, use spl_autoload_register() instead

good point, thanks

**Comment by juek** [comment]
… replace login.php und tool.php and not working

what does the sent / not sent message say?

**Comment by loorlab** [comment]
@juek "There was an error, please try again." + "Javascript is required to access site administration. It appears that you are using an incompatible browser. Make sure you're using a modern browser like Mozilla FireFox or Google Chrome and have javascript enabled."

Possibly it does not send it because there is a possible error in our AWS, the other option is to try another server.

Any option for Mandrill config with Typesetter ?

Thanks !

**Comment by juek** [comment]
> … we would like to know if it is possible to configure Mandrill as the basis for sending default Typesetter notifications.

Currently it is **not** possible without making changes to the CMS core. 

Basically it would be possible to implement a plugin hook that could entirely replace Typesetter's Emailer class with anything else working. Such a plugin then would have to provide functionality and a UI to configure all API requirements from a third party like Mandrill.

**Comment by loorlab** [comment]
Oh ok @juek thanks.

We will try to solve the issue of mailings with the mail() function in AWS.

**Comment by juek** [comment]
I assume you have read [this guide](https://docs.aws.amazon.com/en_us/ses/latest/DeveloperGuide/send-using-smtp-php.html) regarding AWS SES and PHPmailer(?) Especially the Prerequisites section.

**Comment by juek** [comment]
prevent deprecation warning with [this commit](https://github.com/Typesetter/Typesetter/commit/b9444fb7d1c9dfcad5b965904f9c9721e6a5726e)

**Comment by gtbu** [comment]
In do not want to  rub https://github.com/tpbu/PHPMailer-5.27 under Your nose !
But why dont You use my phpmailer-plugin  https://www.typesettercms.com/Plugins/351_PHPMailer_update_5_27 - i have no problems at all with it - the password_hush recovery functions also  after the exchange of login- and tool.php - it just needs php5.4 because of php-zip

**Comment by juek** [comment]
@gtbu: We [are already](https://github.com/Typesetter/Typesetter/tree/master/include/thirdparty/PHPMailer) using PHPmailer 5.2.27. And PHP 5.4 is our new minimum version [since ScssPhp 0.7.6](https://github.com/Typesetter/Typesetter/tree/master/include/thirdparty/Leafo/ScssPhp)
Please check stuff first before you type.
