### ISSUE TITLE
stupid file/dir permissions

### ISSUE THREAD

**Issue by mckaygerhard** [Typesetter/Typesetter#316]
what about that? typesetter spected 777 for dir and 666 fr files? why dont put a messwage that said: "hey where opened to write something here, go to crack on me"

sorry for the noise but it's too obvious!

**Comment by mckaygerhard** [comment]
currently i made a workaround:

install in same SAME path in localwebserver (example if will be `http://domain.com/pepe/` must be then in `http://127.0.0.1/pepe` and so..
do not choose the "combined CSS" neither "combined JS" options..
after install.. move files to destination by ftp/sftp/ssh ...

**Comment by gtbu** [comment]
The 777 and 666 are quite annoying - but if You create a directory with filezilla and transfer files with (s)ftp You will never get 666 or 777 but maximum 755 because of the security - shield of the provider. If You want to be cautious You can put a 755 at the installation directory and subordinate directories and files .
 Except from that an open directory does not necessary open a whole - if it s within the CMS.

**Comment by juek** [comment]
IMO when Typesetter requires 777, your server configuration should be fixed. 
'go to crack on me' … hmm maybe a tiny bit rude. Other suggestions?
