### ISSUE TITLE
Elfinder and editor

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#347]
It is  a great idea to use elfinder now and some editors - and You know about elfinders possibilities to include other directories >(see the elfinder wiki)  - security is no excuse >: joomla has an inbuilt filemanger with editor for the whole repository - and they still live ( my former security problems came from phpmailer - after i updated in summer , the acessses to my contact-site have in my 3 main installations become 5times as much.... of course no mails - and since that time i have never been cracked somehow). 
P.S. What i cannot understand is that You dont include mod_deflate . It is a standard just like trace off and makes the CMS much faster - also for normal users.

**Comment by juek** [comment]
> security is no excuse
 
That's a good one :) That was meant as a joke, wasn't it?

> What i cannot understand is that You dont include mod_deflate.

We cannot include it because it is a server module.

For speed optimization, there is a plethora of possibilities like output compression, caching and optimizing your static assets (including dynamic output filters, eg. to serve webp instead of JPEG/PNG to clients supporting it). It all depends on many factors, from used server software, resources and load up to … well … simply webmaster skills. 

If you ever tried to use mod_pagespeed, where almost everything comes together, you certainly know the complexity in this.

**Comment by juek** [comment]
> It is a standard just like trace off 

If you mean `TraceEnable off` that's also nothing we can do.

**Comment by gtbu** [comment]
No - i thought of multiple roots
https://github.com/Studio-42/elFinder/wiki/Multiple-Roots

**Comment by juek** [comment]
> implemented in permalinks.php line 642

Rewrite rules should go into the <IfModule mod_rewrite.c>…</IfModule> check section. 

But the XST vulnerability your security scanner warnes you about, is merely of historical value since  modern browsers block the TRACE method in XMLHttpRequests

> Elfinder - i thought of multiple roots

That's not a new feature. (el)Finder has had it (and I am using it) for many years. 
If you want to, **you** can add additional roots yourself by editing connector.php, or as part of a Typesetter plugin. But please stop suggesting to make .php files and the system core editable by default (via finder or any other inline editor). It would make many of Typesetter's security measures absurd.
**We will not do that.**

**Comment by juek** [comment]
For mod_deflate: Have you checked if your rule actually makes a difference? It's just because I haven't yet seen a host that provides gzip output compression but has it disabled by default.

**Comment by juek** [comment]
> No chance for hackers

If you think a sole 301 header will prevent anyone to abuse a vulnerable URL, you are probably underestimating your 'hackers'. It might trick some script kiddies' scripts, though.

**Comment by gtbu** [comment]
1. I have universelle-lehre.de with that redirect-filter (though $_SERVER['HTTP_HOST'] is not safe). Well - show me an appended - string that cracks my site ! (I have a full backup.) If the filter cleans from <scri , ascri , escape and other strings, hackers will have a hard time.

2. [Trace](https://www.blackhillsinfosec.com/three-minutes-with-the-http-trace-method/) is only less important for modern browsers.

3. [mod_deflate](https://phlow.de/magazin/wordpress/wordpress-gzip-mod-deflate/) works well as it is implemented . [<IfModule mod_headers.c>](https://httpd.apache.org/docs/2.4/mod/mod_deflate.html) is another possibility.

4. I never thought of implementing such a broad Elfinder-root - but i'd like to have access to the template directories (momentary by sftp) .

**Comment by juek** [comment]
For your trace link: Before you cite all the InfoSec Blogs around the world who have found sth. in conjunction with sth. else under some circumstances. This one is about probing a web application firewall using a crafted trace header. Come on, this is hoster business. If they use a WAF and don't block trace, well, their config could be improved :) 

> How does bbclone get its information from remote?

Probably not from Javascript in the client browser. 

> I never thought of implementing such a broad Elfinder-root

It simply doesn't matter **which .php file** in the stack is editable. If it's writable (= required for editing) and some bad guy wants to do evil sh*t, the process is simple: 1) download a PHP shell 2) game over.

… oh and: I know what mod_deflate is and I'm not going to hack your CMSimpleXH site. o_O

**Comment by juek** [comment]
> but i'd like to have access to the template directories (momentary by sftp)- though several tabs would be better

Sounds as if you're not using WinSCP

**Comment by gtbu** [comment]
1.  WinSCP hs the same problem as SFTP - i have to login with my master-password of the provider .
2. download a PHP shell 2) game over : Sounds as if my site is already cracked... why isnt it ? I know people hwo tried nearly everything (because of the content which is against their interests)....
3. i can harden the filter with if(!ob_start("ob_gzhandler")) ob_start();   If You can give me  ahint how the filter can be made uneffective by php - i would be thankful - just to learn from it and make it safer

**Comment by juek** [comment]
> A php-Shell needs a cli-mode

No.

**Comment by juek** [comment]
But let's just finish this topic. 
We will not implement inline editing for .php files - **template.php is such a file**. If you're only after editing css/scss/less or js files, that's a whole different story. But with .php, it would be an Authenticated Remote Code Execution (RCE). I don't care if other CMS allow it. If an attacker (whichever way) manages to steal your auth cookie, this would be bad enough. But with an authenticated RCE in the CMS, you got **serious problems**. It makes a huge difference.

**Comment by oyejorge** [comment]
> We will not implement inline editing for .php files

100% agreed. The safe way to implement inline editing for templates would be to use something besides php. For example: https://twig.symfony.com/
