### ISSUE TITLE
Narrow window in textarea

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#378]
How can i change the width in the now crippled editor ? (double width - drawable) - evtl. line numbers as i can have with codemirror ( i am stupid and cannot count up to 10374!)

(A.what i else miss is the ability to add a template to a site in another menu-tree directly  as for menu (0) in the pagemanager. Doing it in the site in the top-menu is not very inutitive
B. If You add hooks, a hook which makes adding a dropdown to the top besides options would make things easier. 
C. The dead pen there could start Ckeditor)

**Comment by juek** [comment]
> How can i change the width in the now crippled editor?

If the question is related to elFinder, upcoming changes should make it all work. 

> evtl. line numbers as i can have with codemirror ( i am stupid and cannot count up to 10374!)

No, AFAIK the TextArea editor doesn't feature line numbering. Other editors have been removed because they don't play well with our local versions and Typesetter **must not** rely rely on remote sources.

> A.what i else miss is the ability to add a template to a site in another menu-tree directly as for menu (0) in the pagemanager. Doing it in the site in the top-menu is not very inutitive

I believe we have discussed this before. Inheritance of page layouts cannot be done in multiple different menus because different **menus** may contain the **same pages** – which then would cause conflicts. Therefore layout inheritance is only possible in the main menu.

> B. If You add hooks, a hook which makes adding a dropdown to the top besides options would make things easier.

The $admin_links array is a page variable. It can be modified e.g. in the PageRunScript hook ([example](https://github.com/juek/OpenGraph/blob/master/OpenGraph.php#L385))

> C. The dead pen there could start Ckeditor

We cannot simply start CKeditor without a proper editing target (content section, extra content area). Not every section / area type uses CKE.  But I would agree to remove the symbol because it doesn't actually do anything.

**Comment by mahotilo** [comment]
> the symbol because it doesn't actually do anything.

It symbolizes the editing capability of the next three labels "Sections
Extra Content Layout". At least it should do it.

**Comment by Sestowner** [comment]
> I think, we should insert the pen badge before of each of these labels.

I already has this changes 
![image](https://user-images.githubusercontent.com/36760609/71320829-ae4c3100-24b9-11ea-9f3d-64978985e6c7.png)

Should I make a pull request?

**Comment by juek** [comment]
I would agree but there is already very little space. Some languages use much longer words for the terms, German for exaple: 'Extra Content' = 'Weitere Inhaltsblöcke"

**Comment by juek** [comment]
> Should I make a pull request?

Heck, yes - it's the right thing. Make your pull ;)

**Comment by mahotilo** [comment]
What about Extrainhaltsblöcke? :)

**Comment by juek** [comment]
It even became 'Extra Inhalte' :)

**Comment by gtbu** [comment]
Well - as there will probably no change : I  have the code of the version with 5 editors and will make an own version (not CE) anyway.
