### ISSUE TITLE
Request: GalleryEditorTweaks integration

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#436]
Juergen, 
if you have taken some steps to integrate Colorbox-Extender elements, what do you think about the full integration of [GalleryEditorTweaks](https://github.com/juek/GalleryEditorTweaks) to TS? I always use it.

**Comment by juek** [comment]
I never use it myself and the user experience is, well, let's say 'quite unusual'. With Expandable Editor, the problem of the rather small thumbnails should actually be alleviated.

I think it's a good example of what plugins are good for and I don't want to integrate it in the core.

**Comment by mahotilo** [comment]
Well, if everyone is against...
I can only say one thing. It is very, very convenient for arranging gallery with a lot of dozens of images.

**Comment by juek** [comment]
I have heard from several new users that Typesetter UI has too many options. O_o That sounds strange for an experienced user but people seem to get scared away by buttons they don't immediately understand.
I believe we should really try not to overload the UI and rather keep it as lean as possible. 
Not easy because there are tons of useful things we could add. 

That's why I love plugins, especially the tiny little ones.

**Comment by juek** [comment]
> if you have taken some steps to integrate Colorbox-Extender elements,

No, it's only an additional style. The native Colorbox styles (Example 1-5) are so oldschool, I didn't even like them 10 years ago.

**Comment by mahotilo** [comment]
> No, it's only an additional style. 

...**elements**...
 :)

> I have heard from several new users that Typesetter UI has too many options. O_o

What can I say. It was not my request actually when I asked you about this option some time ago. This was from end users who loved BIG galleries. And they still love them and you plugin.
