### ISSUE TITLE
Ckeditor background broken in site

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#491]
As i already posted similar - the backgrounds of ckeditor in the settings and in the site are different - resulting in very low contrast in the site. This has been fixed now in the CKE-switcher but not in the Cms (ck_area etc.). 
(P.S. You announced today v5.2 - there is meanwhile a scssphp 1.06 and a Jshrink 1.33 )

**Comment by mahotilo** [comment]
It is not broken. This is the result of adaptation of CKEditor to TS. Not only styles from 'inline_edit.css' are involved in this situation but also styles like 'gp_admin_html'. No one wants to change it due to possible avalanche of problems. We already have enough.

That is why I used in-place JS patching of loaded CSS in my plugin. It is almost ready and you can use it to set your favourite CKE theme.  But again, no one gives you a guarantee that it will not break any TS parts.

**Comment by gtbu** [comment]
I cant agree at all  ! The color of the sidebar is inherited into ckeditor . I have  a functioning solution in my ce-version in the inlinedit.css.

**Comment by juek** [comment]
It's really a matter of taste. 
In order to put 'contrast' into numbers:

This ![grafik](https://user-images.githubusercontent.com/704283/72226485-0692c200-3592-11ea-8aa9-120606e93e0f.png) is 30 : 94 (T<sub>m</sub> 0.51)

while this ![grafik](https://user-images.githubusercontent.com/704283/72226498-1ad6bf00-3592-11ea-8a02-a5ffba528be2.png) is 30 : 100 (T<sub>m</sub> 0.54)

That's merely difference of T<sub>m</sub> 0.03 (of max 1)

In terms of luminosities, the kama theme has a significantly lower average contrast.

This is what I'd consider low contrast icons: ![grafik](https://user-images.githubusercontent.com/704283/72226567-c08a2e00-3592-11ea-8e5f-be387d0dface.png) 
It's 82 : 98  (T<sub>m</sub> 0.09) 
Recognize them?

**Comment by mahotilo** [comment]
Juergen
While working on my plugin, I found that many of CKE display problems come from two common style properties.

1. color in
https://github.com/Typesetter/Typesetter/blob/c3d9e35a71402dc9027f9c3714ecf134758916d3/include/css/admin.scss#L98-L99

2. line-height in
https://github.com/Typesetter/Typesetter/blob/c3d9e35a71402dc9027f9c3714ecf134758916d3/include/css/admin.scss#L38-L44

You can also see in comments a hint about another problem.
Maybe it is time to comment this lines?

I remove these properties from document.styleSheets via JS in my plugin. I use it all the time and still see no problems for other parts of the TS interface.

In fact, these two properties are the only reason to use JS in the plugin, all other rules can be easily rewritten with css and !important.

**Comment by juek** [comment]
Why don't you just overrule them by specificity? I don't understand the issue. 
We cannot sacrifice admin CSS normalization for CK Editor.

**Comment by mahotilo** [comment]
> Why don't you just overrule them by specificity? 

Due to styles loading order it is possible only with !important, but I do not want to change CKE themes files.

> We cannot sacrifice admin CSS normalization for CK Editor.

Undoubtedly

**Comment by juek** [comment]
> Due to styles loading order it is possible only with !important.

```
#gp_admin_html #cke_gpcontent a * { 
 	color: #123456;
} 
```

will overrule 

```
#gp_admin_html a * { 
 	color: inherit; 
}
```

by **specificity**, regardless of the load order (= precedence). I don't believe that you need !important.

**Comment by mahotilo** [comment]
It does not help me with CKE themes, because I don't know a proper value to set.

Actually, I need some kind or "revert" value from CSS4:)

This "inherit" broke entire game with other thirdparties css. And as you can see, it is not just for CKE, Fontawesome is involved as well.
/* background: none; prevents other backgrounds from showing. "inherit" wouldn't make sense */ 
//* conflicts with fontawesome */

**Comment by juek** [comment]
> It does not help me with CKE themes, because I don't know a proper value to set.

Shouldn't it be the value the theme would set? It it's overruled you still should be able to see it in inspector.

**Comment by mahotilo** [comment]
> If it's overruled you still should be able to see it in inspector.
Yes, but I am too lazy to do it for a dozen themes:)

**Comment by juek** [comment]
>  line-height: inherit; /* conflicts with fontawesome */ 

We have **a lot** such conflicts that need to be overruled via higher specificity alter on. There is no way to avoid them all. If we didn't normalize them, theme styles would 'shine through' all the time. 
We actually should normalize even more. Bootswatch theme styles frequently make it into CK editor.
[Example](https://github.com/florincatalin/AddScriptPluginTypesetter/issues/1#issuecomment-560076637)

**Comment by mahotilo** [comment]
Yes, BS is a beast:)

Well, I think this discussion just proved my own words

> No one wants to change it due to possible avalanche of problems. We already have enough.

We can continue it, but this issue is not a critical error, so future discussion does not make much  sense.

I propose to close the issue.
