### ISSUE TITLE
Show private pages in Dashboard site menu

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#579]
Should we see a private pages (perhaps with a red background) on the Dashboard (.../Admin) site menu?

If I temporarily closed some page from the user, I still need to have a convenient way to access it. Yes, we have the Notification dialog but it is not connected to the page place on the menu.

**Comment by juek** [comment]
I don't fully understand why private pages are do importance to you. For me they're a tool when extending a website. Sometimes, when a page changes completely, I work on a hidden copy and 'replace' the old page with the new one when it's ready. Sometimes the old page will then go into an archive part of the website. Stuff like that.  I don't switch existing, public pages to 'private' and back on a regular basis.

**Comment by mahotilo** [comment]
> For me they're a tool when extending a website.

For me too, it is mainly a page "under construction". I usually place a private page on the menu in a position where it will appear to users later. So I find it convenient to access it through menu too.

Of course, I can use Page manager. And previously, the top menu on Admin page was limited to 1st level. So it was the only way.
But now you have made this menu more advanced. So, I decided that it could show private pages too. Just an idea.

**Comment by juek** [comment]
> But now you have made this menu more advanced. So, I decided that it could show private pages too. Just an idea.

In fact I only changed it from 1st-level only to 2-level and added some CSS. It uses the same method of menu rendering as all menus do. If we wanted to add private pages, we would have to change Typesetter's menu rendering, e.g. using an additional (boolean) parameter to show private pages under some circumstances. But this would also rise some questions and add additional complexity, such as how to deal with children of private heading pages. 

Since we now have private pages in Notifications, I believe we can access them easily. And there is Page Manager which reflects visibility and it's inheritance quite well. I believe Page Manager should be the only place to manage menu behavior.

**Comment by mahotilo** [comment]
> In fact I only changed it from 1st-level only to 2-level and added some CSS. It uses the same method of menu rendering as all menus do.

Got it.
