### ISSUE TITLE
Bootstrap 4 narrow mode

### ISSUE THREAD

**Issue by gtbu** [Typesetter/Typesetter#618]
The Bootstrap 4 Template has at the left side a site-title. As the width-counter of the template counts the width of the navigation without the width of the title, the hamburger appears already at about 1000px instead of 768 px. 
This template bug is widespread in the internet as at https://bootswatch.com/lumen/ .  The reason for this behaviour is <div class="navbar navbar-expand-lg fixed-top  . -- navbar-expand-sm fixes the problem.
Bootswatch Scss has <nav class="navbar navbar-default navbar-static-top - and has a different reaction without the bug

**Comment by juek** [comment]
It's not a bug. Bootstrap doesn't calculate anything. 

With BS3 it was the `$grid-float-breakpoint` variable value to set the point of collapsing navs, with BS4 it's the `navbar-expand-[breakpoint name]` css class you set.

It all depends on what's your site title (`.navbar-brand`) and the amount, wording and font sizes used for the main menu 1st-level items. 

A small javascript, bound to the window load and resize events, could easily control the menus' collapsed state. AFAIK Bootstrap itself doesn't provide such a script but I'm certain there are hundreds of sources on the web. It's not hard to do.

**Comment by gtbu** [comment]
Sorry but thats not quite true . BT4 has more inherent switches like @media (min-width: 576px) {
  .container {
    max-width: 540px;
  }
}
@media (min-width: 768px) {
  .container {
    max-width: 720px;
  }
}
than BT3 . And :
<div class="collapse navbar-collapse navbar-right" id="navbarResponsive">
The div is controlled with @media ( ....
adding .sm switches to the top switches  it nearly off.  The problem is lg
Example http://typesetter5.bplaced.net/smartstrap4 
It is not acceptable for small devices that the hamburger comes at 1000px instead of 768. What for would then the 5 differentiated steps in BT4 be introduced.

**Comment by juek** [comment]
> Sorry but thats not quite true.

Specify or quote what's not true :)

For the rest: what you're calling 'switches' are media query breakpoints. They form the basis for responsive design and have been there for many years. Nothing new except that Bootstrap 4 in particular added one in between the former BS3 xs and sm, keeping the nomenclature while shifting the widths (IMO an exceptionally troublesome decision).

> Its not a CMS-Bug - its a design-bug of the template.

It's simply up to you to change it. 
If you prefer a main nav with only 3-4 rather short 1st-level items (which I do, BTW), `navbar-expand-lg` is not optimal and you might want to go for `navbar-expand-md`, maybe even `navbar-expand-sm`, depending on the width of your site title or brand logo.

Most websites that I create grow to 5-7 main navigation items within a short time, which leads to an ugly line break in the menu when using `navbar-expand-md` or smaller (e.g. check https://www.kabarettarchiv.at, https://www.recoveriX.at. https://www.br41n.io is Bootstrap 3 but it would even require more than `-lg` if it was BS4, depending on how many events are currently listed)

That's why I stick to it: it's not a bug.

**Comment by juek** [comment]
BTW: 

![grafik](https://user-images.githubusercontent.com/704283/77333898-5fb26b00-6d24-11ea-8138-1b2948d67a6e.png)
Sreenshot of http://typesetter5.bplaced.net/smartstrap4. That's really intended?

**Comment by gtbu** [comment]
If the navigation is long then it is better to have 2 lines instead of a single dropdown as in 300px-mode. For me (and evtl. other users) counts the usability !

**Comment by mahotilo** [comment]
> If the navigation is long then it is better to have 2 lines instead of a single nested dropdown

It definitely depends on the design. Personally, I prefer to see "hamburger" as a lesser evil. And do not forget that most site visitors are now mobile users. They do not have problems with "hamburger" at any screen resolution all at.

**Comment by gtbu** [comment]
They also use the 90-degree tiwsted broad handy mode - or shift the site from left to right.

**Comment by mahotilo** [comment]
> If You have a deep sitestructure than 2 lines are better

Or side menu like in Cajon_Scss

**Comment by juek** [comment]
All in all it's a matter of what you want to achieve. Usability is one aspect, aesthetics (or call it taste) is another - while they should, they will not always lead to the same results. There is no right and wrong in design. If there was, we'd would let algorithms do it instead of designers.  

In some cases, e.g. landing pages, you might even want to generally hide your main navigation behind a hamburger in order to focus on your Call-To-Actions (CTAs).

To quote UsabilityGeek:
> “Pair it with a strong CTA:. The only way it is beneficial to hide your menu is if you are providing a clear path elsewhere. This can either be in the header area, an in-context button or link within the body of the page, or both” ([source](https://usabilitygeek.com/making-case-for-desktop-hamburger-menu))

**Comment by juek** [comment]
Fun fact to top it off… 
https://usabilitygeek.com 'hamburgers' below 1023px, which is even wider than BS4's lg breakpoint (992px). If you ask me, for obvious reasons.
