### ISSUE TITLE
$gp.loading(); in user mode

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#619]
I use 
> 		...
> 		$gp.loading();
> 		$gp.postC(href,data);
> 
in my script. 
Everything works great in admin mode. The spinner rotates and the post is posted. 
In user mode, `$gp.postC()` also works fine, but `$gp.loading();` gives only jitter instead of the spinner.

Is it problem of my code or `$gp.loading();` is not intended to be used in user mode?

**Comment by juek** [comment]
> Is it problem of my code or $gp.loading(); is not intended to be used in user mode?

It's definitely not made for user mode. The css is missing and Font Awesome used by the spinner icon also doesn't load by default. 

But, since the function is already loaded, you could easily supplement the missing parts. 

IMO, when you create custom modals or ajaxing content they should come with their own overlays. Simply for better maintainability and customization.

**Comment by mahotilo** [comment]
Thx
