### ISSUE TITLE
Poll: Page name transliteration

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#641]
We already have some automation to convert spaces to "_" or "-" in page URL via "URL Space Character". 
How about adding an option to page ~~name~~ URL transliteration into pure Latin? 
E.g., as described [here](https://www.php.net/manual/en/transliterator.transliterate.php).

```
<?php
var_dump(transliterator_transliterate('Any-Latin; Latin-ASCII; Lower()', "A æ Übérmensch på høyeste nivå! И я люблю PHP! ﬁ"));
// string(41) "a ae ubermensch pa hoyeste niva! i a lublu php! fi"
?>
```
It will be helpful for those who do not like eventually seeing something like this `http://****.com.ua/%D0%A4%D1%83%D1%80%D1%88%D0%B5%D1%82`
And I think that this will be helpful not only for Cyrillic, but for umlauts and ligatures too.

UPD
Or, maybe, we already have some hook in a proper place? :)

**Comment by juek** [comment]
> Or, maybe, we already have some hook in a proper place?

We [actually have](https://github.com/Typesetter/Typesetter/blob/master/include/admin/Tools.php#L1237) that

**Comment by mahotilo** [comment]
So, it could be done with a plugin.
Thx

**Comment by juek** [comment]
> So, it could be done with a plugin.

Yep. Shall I add a POC the /addons folder?

**Comment by mahotilo** [comment]
Yes, if it's not too much work. It will be great help!

**Comment by mahotilo** [comment]
I have tried it. You  --SimilarTitles-Example is easy to convert:)
Hook works basically. I have transliterated URL. But interface part are showing URL before transliteration
Maybe I should  take a closer look at the hook arguments.

![image](https://user-images.githubusercontent.com/14929385/84432765-f6ad0600-ac35-11ea-99b2-f7e43ccaf2dc.png)

**Comment by juek** [comment]
The Rename/Details dialog has its own [LabelToSlug JS function](https://github.com/Typesetter/Typesetter/blob/master/include/js/admin.js#L1749-L1769), which basically resembles the server-side counterpart. Unfortunately it cannot call the hook. 

To make the behavior consistent, we'd have to change the JS function in order to get the slug via an AJAX request from the server. The results would show with a little delay. 

Feasible? Yes. 
Technically reasonable? Absolutely. 
Worth the hassle? Questionable ;)

**Comment by mahotilo** [comment]
Yes, it should be carefully considered.
I think the issue can be closed again:)
Thx.
